env: SKIP_PREFLIGHT_CHECK=true
language: node_js
node_js:
  - '12'
before_script:
  - npm i
script:
  - npm run lint
before_deploy:
  - npm build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
